steps:
  #Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${CONTAINER_NAME}:${VERSION}', '.']
    id: 'build-image-myapp'
    waitFor: ['-']  # The '-' indicates that this step begins immediately.
  #Push the image to google container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${CONTAINER_NAME}:${VERSION}']
    id: 'push-image-to-container-registry'
    waitFor: ['build-image-myapp']

substitutions:
  #GCP Specific configuration. Please DON'T change anything
  PROJECT_ID: ${_PROJECT_ID}
  ZONE_NAME: us-central1-c
  
  #Repository Specific configuration. DevOps can change this settings
  DEPLOYMENT_NAME: hello-world-fastapi
  CONTAINER_NAME: hello-world-fastapi 
  
  # Developers ONLY change
  VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'