steps:
  #Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CONTAINER_NAME}:${_VERSION}', '.']
    id: 'build-image-myapp'
    waitFor: ['-']  # The '-' indicates that this step begins immediately.
  #Push the image to google container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_CONTAINER_NAME}:${_VERSION}']
    id: 'push-image-to-container-registry'
    waitFor: ['build-image-myapp']

substitutions:
  #GCP Specific configuration. Please DON'T change anything
  # If you don't pass _PROJECT_ID here then add this variable during creation of cloud build trigger.
  # _PROJECT_ID: YOUR_PROJECT_ID
  _ZONE: us-central1-c
  
  #Repository Specific configuration. DevOps can change this settings
  _DEPLOYMENT_NAME: hello-world-fastapi
  _CONTAINER_NAME: hello-world-fastapi 
  
  # Developers ONLY change
  _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'